### ISSUE TITLE
Import cbor2 not cbor

### ISSUE THREAD

**Issue by mcepl** [crossbario/autobahn-python#1154]
https://github.com/crossbario/autobahn-python/blob/e883eee48a5d796e22e86a43b5f4e43e419f6d9c/autobahn/wamp/message.py#L39

Finish process started in #926 and #722. Probably related to #1125 as well.

**Comment by oberstet** [comment]
won't fix: cbor2 is a lot slower on pypy compared to cbor

**Comment by meejah** [comment]
Ohhh, hmm. That's lazy grep'ing on my part: you have to turn on `AUTOBAHN_USE_CBOR2` to get cbor2 to be used? I was confused by "there's both cbor and cbor2 imports" ...

**Comment by oberstet** [comment]
* the line linked above isn't even releated to WAMP-cbor, but WAMP-flatbuffers, because with WAMP-flatbuffers, the WAMP message is flatbuffers, but the _app payload_ (that is transported in a uint8[] at the FB level) must be somehow serialized - and that is currently fixed at cbor
* yes, AB _can_ use both cbor and cbor2 for WAMP-cbor, and the latter can be activated using AUTOBAHN_USE_CBOR2

**Comment by oberstet** [comment]
rgd performance of cbor vs cbor2 (for WAMP-cbor): https://crossbario.com/docs/benchmarks/serialization/index.html
