### ISSUE TITLE
setup.py install puts binary module to arch-independent directory

### ISSUE THREAD

**Issue by mcepl** [crossbario/autobahn-python#1155]
setup.py install installs to sitelib directtories, not sitearch.
Specifically python* setup.py install installs on Linux everything to /usr/lib not to /usr/lib64. Specifically, _nvx_utf8validator.so should be in arch-dependent directory.

Also, see https://src.fedoraproject.org/rpms/python-autobahn/blob/master/f/python-autobahn.spec where files also end in %{python3_sitelib}, so it is not just openSUSE problem, but apparently my colleagues at RedHat missed that. @hroncok, what do you think?

Ah, correction, our colleagues at RedHat don't see it, because they don't set ``AUTOBAHN_USE_NVX``. How much does it speed things up?

**Comment by hroncok** [comment]
@mcapl I'm not responsible to all Python packages in Fedora and I don't maintain autobahn nor i know anything about it.

**Comment by oberstet** [comment]
* NVX is "work in progress" - don't set `AUTOBAHN_USE_NVX` is the best for now. we introduced this env var now, because we recently touched the serializer code parts
* the speed ups can be huge, but it is not yet production ready, and currently amd64 only (SSE2 and SSE4.1). we will finish and ship it though at one point, since XOR masking and UTF8 validation is the main (measured) CPU bottleneck of Autobahn (at the WebSocket level)
* sorry if that sounds harsh, but: I don't care about SuSE or RedHat packaging policies - distro packaging of python packages is "wrong" IMO
* **If you claim that we incorrectly package Autobahn from a _Python_ perspective (might be the case indeed), then we will of course fix that.** we do want to be good citizens in the Python universe
* fwiw, we have started to package our stuff as `snaps`, because that follows a vendor-packaging approach which cuts out the distro between us and our users - `snaps` are awesome

**Comment by mcepl** [comment]
> @mcapl I'm not responsible for all Python packages in Fedora and I don't maintain autobahn nor I know anything about it.

You are just the last one who committed to its git? Anyway, sorry for bothering then.

**Comment by mcepl** [comment]
> * sorry if that sounds harsh, but: I don't care about SuSE or RedHat packaging policies - distro packaging of python packages is "wrong" IMO

OK, I hear you. I think you are completely wrong, but I understand we are on our own here. Duly noted.

> If you claim that we incorrectly package Autobahn from a Python perspective (might be the case indeed), then we will of course fix that. we do want to be good citizens in the Python universe.

Yes, that's what I claim, but perhaps if NYX (and it is the only binary module) is still WIP that it is understandable. I will get rid of that variable and just let it be.
