### ISSUE TITLE
time.clock is removed in Python 3.8

### ISSUE THREAD

**Issue by tirkarthi** [crossbario/autobahn-python#1193]
`time.clock` was deprecated in 3.3 and was removed in 3.8 with PR https://github.com/python/cpython/pull/13270 . I think below line might cause incompatibility in 3.8 on Windows so I am creating an issue for the same.

https://github.com/crossbario/autobahn-python/blob/87ea1cca817dbc41a783b6b27483197bfa69ac78/autobahn/util.py#L466

Thanks

**Comment by ivankravets** [comment]
Hi @oberstet 
Do you plan to fix this issue? We receive a lot of issues related to `time.clock` when Python 3.8 is installed.

**Comment by oberstet** [comment]
from quick reading, seems like

* `time.clock` is depr. since 3.8 on all platforms
* autobahn only uses `time.clock` when on windows

so we should extend this line (and only that)

https://github.com/crossbario/autobahn-python/blob/87ea1cca817dbc41a783b6b27483197bfa69ac78/autobahn/util.py#L466

to use

https://docs.python.org/3.3/library/time.html#time.perf_counter

when on >=3.8 (and on windows, which is already the case for the code line I linked)

**Comment by ivankravets** [comment]
Yes, we patched `autobahn-python` with `time.perf_counter` for pre-compiled packages.

**Comment by om26er** [comment]
fixed via https://github.com/crossbario/autobahn-python/pull/1259/files
