### ISSUE TITLE
Adjust CI to deploy wheels to PyPI

### ISSUE THREAD

**Issue by jcpunk** [crossbario/autobahn-python#1606]
In a minimal container I'm building I hit:
```
DEPRECATION: autobahn is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
```

Can this project be updated to contain a pyproject.toml and have wheels up at https://pypi.org/project/autobahn/#files

**Comment by oberstet** [comment]
sure: https://pypi.org/project/autobahn/

**Comment by jcpunk** [comment]
I'll confess a bit of puzzlement at this being closed with just that link...

**Comment by oberstet** [comment]
yeah, sorry, I'm just personally fed up with / don't care about distro packaging.

I had a quick look though, and it seems I forgot: we do have wheels and publish those

https://github.com/crossbario/autobahn-python/blob/a99ff5dd4e54595bd13ffdcf92d72e0737246e38/deploy.sh#L28
https://github.com/crossbario/autobahn-python/blob/a99ff5dd4e54595bd13ffdcf92d72e0737246e38/.github/workflows/deploy.yml#L79

just not to PyPI. for other reasons, above wheel deployment target isn't required anymore, and best would probably indeed be publishing wheels to PyPI.

since the Python wheel packaging requires building wheels per-target, this will then lead to even more work. I'll reopen the package, maybe someone fixes it ..

**Comment by oberstet** [comment]
fwiw, as you mentioned docker, those are readily available herehttps://hub.docker.com/r/crossbario/autobahn-python/tags
