### ISSUE TITLE
Strict bytes/unicode type checking in the public API

### ISSUE THREAD

**Issue by tardyp** [crossbario/autobahn-python#455]
The fix is obvious here, I am not sure if I shall submit a PR for that.

wamp/types.py contains uncoherent type checking.

```
    assert(match is None or (type(match) == six.text_type and match in [u'exact', u'prefix', u'wildcard']))
    assert(details_arg is None or type(details_arg) == str)
```

Sometimes its shall be unicode, and sometimes should be string.

I'm happy to put from **future** import unicode_literals on top of my files, but this breaks for details_args="details". Need to write details_args=str("details")

**Comment by oberstet** [comment]
The type checking in general might be inconsistent in general. We should check that systematically and make it consistent.

Regarding this particular case:

`details_arg` is a Python identifier .. the name of the parameter of a registered user procedure under which one wants to receive details. Actually, the more tight check would be "is details_arg a valid Python identifier" (otherwise it can't be a parameter name). I guess Python identifiers can't be Unicode anyway? Python 3 has `"foobar".isidentifier()` - http://stackoverflow.com/a/29586366/884770

**Comment by meejah** [comment]
regarding ``details_arg`` specifically: perhaps an API-breaking change to make it just ``wamp_details=True`` or similar (and hard-code what the kwarg is, like ``details``) would be better....?

**Comment by oberstet** [comment]
@meejah Yep, I agree that `details_arg` is probably over-engineered. In almost all real world cases there is no need to specify the name of the parameter under which to receive the details. So it would be sufficient to have a binary flag. The naming of that could be `wamp_details`, `receive_details`, `with_details` or simply `details`.

And yes, that's API break. And since there are more places where "naming" isn't exactly pretty or consistent, I think we should do a systematic review of the public API - in particular rgd naming, and then only do 1 major release breaking API and cleaning up all those things.

E.g. we could do: make everything really PEP8. Including naming. And private vars. Those 2 areas are the last missing to make AB fully PEP8.

I regret not having followed that from the very very beginning. Well. But we still have a chance before release 1.0.

**Comment by hawkowl** [comment]
The Twisted ones should still really follow the Twisted naming convention though (even if it's a renaming shim).

**Comment by oberstet** [comment]
> The Twisted ones ...

What Twisted ones?

**Comment by hawkowl** [comment]
The Twisted portions of Autobahn -- eg. onJoin() in the Twisted app session, on_join in the asyncio one, so both fit.

**Comment by oberstet** [comment]
No, all of the public API should follow PEP8.

**Comment by oberstet** [comment]
So we would check URIs, wherever they appear in the public API for unicode. No exception to this, and no auto coercing into unicode.

These checks should raise exceptions (not use assert). See [here](https://github.com/tavendo/AutobahnPython/blob/master/DEVELOPERS.md).

In particular, this pattern:

```python
import six
from autobahn.wamp import ApplicationError

def foo(uri):
    if type(uri) != six.text_type:
        raise ApplicationError(ApplicationError.INVALID_URI,
                               u"URIs for foo() must be unicode - got {} instead".format(type(uri)))
```

Now, we might also have specific exception classes that derive from `ApplicationError`, like `InvalidUri`: https://github.com/tavendo/AutobahnPython/blob/master/autobahn/wamp/exception.py#L227

This isn't hashed out yet though:
* the decorators thing isn't set in stone yet
* the prototype we have for `InvalidUri` doesn't allow to provide an error message like in the snippet above

**Comment by oberstet** [comment]
I've looked over this again, and I think:

1) the changing from `assert` to a `raise` based idiom for parameter type checking is already tracked in a different issue (we should not do that here): 

2) the switch from having a configurable `details_arg` (which was the origin of the type checking _appearing_ to be inconsistent) to a `details=True|False` that then calls the user handler with a non-configurable `details` named kw parameter (if the former flag was set `True`) is an API break, and we should do that in a concerted effort together with the LTS API stuff

3) I will go over the code to check that URIs parameters are treated consistently, in behavior, and in code style.

Eg:

```python
(cpy3_1) oberstet@thinkpad-t430s:~/scm/crossbario/autobahn-python$ find . -name "*.py" -exec grep -Hi "== str" {} \;
./autobahn/wamp/protocol.py:        if six.PY2 and type(realm) == str:
./autobahn/wamp/protocol.py:        if six.PY2 and type(authid) == str:
./autobahn/wamp/protocol.py:        if six.PY2 and type(authrole) == str:
./autobahn/wamp/protocol.py:        if six.PY2 and type(topic) == str:
./autobahn/wamp/protocol.py:        if topic and six.PY2 and type(topic) == str:
./autobahn/wamp/protocol.py:        if six.PY2 and type(procedure) == str:
./autobahn/wamp/protocol.py:        if procedure and six.PY2 and type(procedure) == str:
./autobahn/wamp/types.py:        assert(details_arg is None or type(details_arg) == str)
./autobahn/wamp/types.py:        assert(details_arg is None or type(details_arg) == str)
(cpy3_1) oberstet@thinkpad-t430s:~/scm/crossbario/autobahn-python$ find . -name "*.py" -exec grep -Hi "==str" {} \;
(cpy3_1) oberstet@thinkpad-t430s:~/scm/crossbario/autobahn-python$ 
```

The`six.PY2` stuff is old-style. Should be cleaned up using `six.text_type` and no auto-coercion.
