### ISSUE TITLE
secure websockets broken with latest twisted

### ISSUE THREAD

**Issue by sherpya** [crossbario/autobahn-python#535]
I'm using twisted 15.4.0, in autobhan/twisted/wamp.py (setupService)

you need this code, but I don't known if it breaks old twisted versions, also it would be nice to pass the context e.g. to add certificates

```python
            if isSecure:
                from twisted.application.internet import SSLClient
                from twisted.internet import ssl
                contextFactory = ssl.ClientContextFactory()
                client = SSLClient(host, port, transport_factory, contextFactory)
            else:
                from twisted.application.internet import TCPClient
                client = TCPClient(host, port, transport_factory)

            client.setServiceParent(self)
```

**Comment by sherpya** [comment]
I propose something like
```
diff --git a/autobahn/twisted/wamp.py b/autobahn/twisted/wamp.py
index 6d4b8bb..f3684ed 100644
--- a/autobahn/twisted/wamp.py
+++ b/autobahn/twisted/wamp.py
@@ -548,7 +548,7 @@ if service:
         """
         factory = WampWebSocketClientFactory
 
-        def __init__(self, url, realm, make, extra=None,
+        def __init__(self, url, realm, make, contextFactory=None, extra=None,
                      debug=False, debug_wamp=False, debug_app=False):
             """
 
@@ -573,6 +573,7 @@ if service:
             """
             self.url = url
             self.realm = realm
+            self.contextFactory = contextFactory
             self.extra = extra or dict()
             self.debug = debug
             self.debug_wamp = debug_wamp
@@ -602,12 +603,14 @@ if service:
 
             if isSecure:
                 from twisted.application.internet import SSLClient
-                clientClass = SSLClient
+                if self.contextFactory is None:
+                    from twisted.internet import ssl
+                    self.contextFactory = ssl.ClientContextFactory()
+                client = SSLClient(host, port, transport_factory, self.contextFactory)
             else:
                 from twisted.application.internet import TCPClient
-                clientClass = TCPClient
+                client = TCPClient(host, port, transport_factory)
 
-            client = clientClass(host, port, transport_factory)
             client.setServiceParent(self)
```

**Comment by meejah** [comment]
We are working on a better API for ``ApplicationRunner``, including support for retrying, reconnecting and SSL options. Passing a context factory (should be ``context_factory``) is certainly a good first step though!

Additionally, for the base case of "I'm a client and want TLS but don't care about the details", I think the API we want to call is ``twisted.internet.ssl.optionsForClientTLS()`` as the ``context=`` to ``SSL4ClientEndpoint`` since endpoints are the "new" API for this sort of thing.

**Comment by sherpya** [comment]
unfortunately the current code is broken (SSLClient needs an additional parameter) and without a contextFactory it will accept all certificates, so a quick fix would be nice

**Comment by meejah** [comment]
I *believe* the less-disruptive quick-fix would be pass the result of calling ``optionsForClientTLS`` https://twistedmatrix.com/documents/15.4.0/api/twisted.internet.ssl.optionsForClientTLS.html with a hostname parsed from the ``url``.

**Comment by sherpya** [comment]
yes, I pass a similar context in my code to validate against my self signed certificate

**Comment by meejah** [comment]
Hmm, actually I don't see a problem providing a ``context_factory`` to pass to SSLClient since this is *just* for the ``Service`` API, which isn't using (and won't be affected by) any ``ApplicationRunner`` changes.

@oberstet what do you think? Something like this: https://github.com/crossbario/autobahn-python/compare/master...meejah:issue535-service-ssl

(I haven't tested the above)

**Comment by meejah** [comment]
BTW, are you sure it accepts any cert without that argument? I thought 15.x did "browser-like" verification by default?

**Comment by oberstet** [comment]
fixed now
