### ISSUE TITLE
Expose auto-reconnect knobs

### ISSUE THREAD

**Issue by oberstet** [crossbario/autobahn-python#588]
We still have the "new API" issue open, where a whole new, "better" API was discussed - we no final conclusion yet. But we need auto-reconnect now. So here is a pragmatic approach with only slight API changes, which would allow to handle reconnects, as well as more flexibility.
- Rename `autobahn.twisted.wamp.ApplicationSession` to `autobahn.twisted.wamp.Component`
- Rename `autobahn.twisted.wamp.ApplicationRunner` to `autobahn.twisted.wamp.Client`
- A `Client` can have instances of `Components` be added, and then the `Client` can be started:

``` python
component = Component(extra={u'foo': u'bar'})
client = Client(url=u'ws://localhost:8080/ws')
client.connect(realm=u'realm1', autoreconnect=True)
react(client.start)
```

The `Client.start()` method returns a `Deferred` that fires when the `Component.onDisconnect()` callback ends and does not recall into `Component.connect()`.

The `Component.onDisconnect()` callback can call `Component.connect()` to reconnect, or can return a plain or deferred value or exception.

When `Component.onDisconnect()` ends, the `Client.start()` method will end.

The `autoreconnect`  option on the `Client.connect()` method activates a default implementation of `Component.onDisconnect()` which does not end, but reconnects the component.

**Comment by oberstet** [comment]
Probably, we should take the chance and rename `Component.onDisconnect` to `Component.on_disconnect` and the like as well here. It's not _really_ about reconnect, but the reconnect feature only makes sense IMO if the API is changed a little, and we want to take that chance to do the PEP8 naming cleanup as well. Because otherwise we'd had two API breaks. Better ship / bundle all changes ..

**Comment by meejah** [comment]
Yes, I agree if renaming ApplicationSession->Component then we should do the PEP8 naming too.

However, I'm not completely sold on the ``Client.start`` as an API: a helper-method style to run is better than introducing a subclass-only API, IMO. It's been a while since I looked at the new-api things, but something like https://github.com/meejah/AutobahnPython/blob/refactor-transport--newapi-examples/autobahn/twisted/wamp.py#L266 (ignoring whether that's actually the API, or actually the newest version of that idea). In that context, ``.open()`` was the entry-point to call ``react()`` on; this basically called ``.start`` on Connection objects, which only callback'd when they were "done, cleanly" and otherwise would errback.

That is, basically provide a 2-layer API: if you use the ``.start/.connect`` or whatever API, you get a Deferred that either errbacks (if something at all went wrong) or callbacks if everything went fine (e.g. usually "never" but if you decide to exit cleanly, that's the route). So this is where I'm a bit unsure: making that method a thing that's suitable to pass to ``react()`` might constrain it from being an API that can be "upgraded" to a future ``.run()`` helper...But, essentially I *believe* the ``.start`` you propose above is basically the same as ``Connection.start`` in many versions of the new-api...so maybe it will be fine :)

Overall, I think any convenience method to pass to ``react`` provided should be a "bare" helper method (and my colour for that bikeshed would be ``autobahn.twisted.wamp.run`` or similar). This separates the concerns (e.g. "start up my event-loop with these Connection(s) please" versus "connect this Connection, and tell my if it ends or has a problem").

I also think it will force a nicer and more-flexible API on Connection/Client (or equivalent) instances (e.g. ``run([client0, client1])`` etc...). When I was thinking about ``Connection``, that to me abstracted "all connection details" about one thing (urls, credentials, options, etc) and in that way it completely makes sense to want to "run" more than one of those...

**Comment by manatlan** [comment]
... But we need auto-reconnect now ...

For sure ... I really think there are a lot of autobahn-python new users, which could be completely disappointed about this auto-reconnect missing feature.
Nowadays, in the connected area, with smartphones which loose frequently the connection ... an autobahn component is useless.

I really think it's really most important than a new api

**Comment by FirefighterBlu3** [comment]
indeed. i'd really love to swap out my brutish event loop hack for auto reconnect for something much cleaner and native to the library

**Comment by FirefighterBlu3** [comment]
@oberstet how will this look for native asyncio implementations?

**Comment by oberstet** [comment]
Auto-reconnect is available in the Twisted flavor of ApplicationRunner.

What is missing is:

1. expose the knobs to control auto-reconnect (initial delay, jitter etc) - see [here](https://github.com/crossbario/autobahn-python/blob/master/autobahn/twisted/wamp.py#L331)
2. asyncio

**Comment by oberstet** [comment]
The knobs exposed (and the semantics) should follow the ones in ABJS as closely as possible / sensible.

**Comment by oberstet** [comment]
this has been fixed, pls see https://github.com/crossbario/autobahn-python/blob/299a6560cc8bd8e3ad7c02acf6cf15cf15cee87b/autobahn/twisted/wamp.py#L118
