### ISSUE TITLE
Logging architecture is difficult to manage

### ISSUE THREAD

**Issue by calston** [crossbario/autobahn-python#616]
With almost every class reimplementing the attribute `log = txaio.make_logger()` this leaves no clear way to set a global logging level when using `twistd` as one should without having to re-implement the entire logging subsystem yourself.

For starters it should be possible to pass overriding options (like shutting debug up) to the constructor, and thereafter the logging configuration should inherit onto other classes - that said the architecture appears to be written into a corner in actually implementing that.

**Comment by oberstet** [comment]
Please see here: http://txaio.readthedocs.org/en/latest/programming-guide.html#logging

**Comment by calston** [comment]
Am I seeing there (which I already read) exactly the problem which I described in that I have to call start_logging with the arguments in an unknown part of my twisted service startup but then I blow away the existing service logger I have?

**Comment by oberstet** [comment]
@calston Yeah, agree. It should use an existing old school Twisted logger if there is one around. No clue if that is working or not, as I am not using twistd or Twisted services. @meejah or @hawkowl might know ?

**Comment by meejah** [comment]
Without calling ``start_logging``, it should inter-op with Twisted logging (if you're using Twisted) or with stdlib logging (if you're using asyncio).

It is slightly more efficient if you can call ``txaio.start_logging``, as it re-binds unused log functions to a no-op in all txaio-created logging instances. However recently, @hawkowl added ``set_global_log_level`` to do "just" this piece of it for all txaio-instantiated loggers (that's all the things from ``make_logger``).

Probably the programming guide needs to be updated to make your use-case more obvious. I believe all you'll want to do is call ``txaio.set_global_log_level()`` during your service start-up if you want logging at a level besides the default (``info``).

**Comment by meejah** [comment]
Note that you shouldn't *have* to call ``set_global_log_level()`` at all (but I haven't tested this since @hawkowl's most recent changes). If you're using twisted's logger yourself, it should work like this:

 - a txaio logger gets, e.g., a .debug() message;
 - txaio emits this message;
 - then your observer sees it and takes action according to its level.

If you call ``txaio.set_global_log_level()`` then your observer simply won't see an "over level" message at all (i.e. it's never emitted, because ``.debug()`` became a no-op).
