### ISSUE TITLE
ApplicationRunner API improvements

### ISSUE THREAD

**Issue by meejah** [crossbario/autobahn-python#674]
Currently, the "usual" way to run an `ApplicationSession`-derived component is via the `ApplicationRunner` API. This lumps together several things:
- creates the component (ComponentConfig + instantiating the session)
- possibly sets up TLS options, if `wss://` URI
- starts the event-loop (`reactor.run()` for Twisted or `run_until_complete` in asyncio).
- starts logging (via `txaio.start_logging`).
- handles several error-cases

This becomes awkward for certain use-cases, and e.g. spawned a `start_reactor=bool` kwarg for the Twisted version (which also lumps in logging, because `start_logging` is only called if it starts the reactor itself).
- users wanting to start their own logging (e.g. https://github.com/crossbario/txaio/issues/75#issuecomment-216651341)
- users wanting to run the event-loop elsewhere (e.g. `start_reactor=` kwarg)
- users who want to handle errors themselves

I am filing this bug to collect these use-cases as a way to improve the "I wish to run a component" API to ensure they're covered.

**Comment by oberstet** [comment]
@meejah good idea to have a "meta bug" for the actual, complete use case (what people want to do)!

**Comment by mayerwin** [comment]
It is indeed very annoying not to be able to control logging (I have been struggling to find why logging was duplicate), and the event loop (most asyncio code allows to pass an arbitrary loop to be used).

**Comment by potens1** [comment]
I subscribe to this. IMHO, the ApplicationRunner does to much of magic (well, it's not magic at all, the code is very short and easy to understand, but you have to check what is going on here when you are discovering autobahn-python), i.e. running the loop and closing the loop. I think this should be done explicitly by the user (or there should be a way to do it manually, if the default is doing all the machinery of the loop) because, when writing software that has already asyncio components, it's a bit strange not being able to start the loop by yourself, or adding an autobahn component to an already running loop/software, more over, when the connection to the router is lost, the complete program stops (because the loop is stopped), and, if i.e. you want to do asyncio things to clean stuffs (i.e, start an asyncio commit to db, continue running tasks and restart a new session,...) you can't.
I know you can subclass ApplicationRunner to change all those things, by I'm more or less convinced that's what will happen to the majority of users, rewriting ApplicationRunner in a way or another, so, maybe there is some value to rethink the thing.
I also find the documentation should emphase ApplicationRunner is designed for quick tests and development and is likely to be subclassed for more complex setup.

**Comment by mayerwin** [comment]
Yes, to make it work for me, I ended up copying the code of ApplicationRunner (which is quite short) and removing the call to start_logging. Generally of course I try to abide by the package code as much as possible (so I was reluctant to do this).

While it is good to have this kind of quick start example to help people have something up and running (it worked well for me when testing initially), it should be made clearer that it is not meant for production use. Or it should support configuration options to change all the aspects managed by this class (logging, loop...). 
I also found it not very easily pluggable to existing infrastructure (the whole app has to be included in the ApplicationRunner class, so for my use case I ended up adding callback parameters to the constructor to consume API events).

**Comment by potens1** [comment]
I just created a pull request about a little rewriting of ApplicationRunner to let users manage the event loop. If users still want to use ApllicationRunner.run, it should not change anything for them (say the tests)
See https://github.com/crossbario/autobahn-python/pull/694

**Comment by petri** [comment]
I have an use case whereby (on Windows7) I need to to control the loop based on whether a win32event is triggered. So I have to subclass ApplicationRunner and override the loop handling in its `run` method because the runner assumes total control. IMHO, the ApplicationRunner does too much right now.

**Comment by oberstet** [comment]
@petri I'm not really happy with ApplicationRunner too. It provides a quick and easy way of running stuff, but then you loose some control about details. Not sure if we can have both, or should simply document it's intended (limited) use better like @potens1 and @mayerwin seem to suggest. API design is hard.

**Comment by oberstet** [comment]
subseded/fixed in https://github.com/crossbario/autobahn-python/issues/964
