### ISSUE TITLE
Unexpected processing order of received messages

### ISSUE THREAD

**Issue by aberres** [crossbario/autobahn-python#862]
First of all: I guess we have no bug here, but a behavior which might need some documentation (if not existing yet).

Consider the following case:
A client subscribes to a topic and calls a function. The result of the function is awaited.

Now the server first publishes something on the topic and instantly afterward returns the result of the function call.

What happens now on the client side is that first the subscription handler is fired (synchronously I guess) and then once the future is resolved the function call result is processed.

The behavior can be easily simulated:
#### Client:
```
async def onJoin(self, details):
    await self.subscribe(self.handle_change, 'changed')

    all_changes_future = self.call('all_changes')
    await self.call('make_change', 'a change')

    all_changes = await all_changes_future

    print('all_changes: ', all_changes)

def handle_change(self, change):
    logging.info('change# %s', change)
```

#### Server
```
@wamp.register('make_change')
def make_change(self, the_change):
    print('make_change')
    self.all_changes.append(the_change)

    self.publish('changed', the_change)

    return the_change

@wamp.register('all_changes')
def all_changes(self):
    print('all_changes')
    return self.all_changes
```

Complete example code can be found here: https://gist.github.com/aberres/0c5b356190991b1d0204bbf5ca399e05

The server will print
> all_changes
> make_change

while we see
> change:  a change
> all_changes:  ['a change', 'a change']

on the client side.

I'd say technically this behavior is correct. It might be unexpected for a developer though.

When could this be a problem?
I noticed this in practice when I have a function to retrieve the current state of some objects and send around any changes as delta.
Now there is a possibility for a race the moment the client registers.
The complete state might not have been handled yet while a subscription is already processed.

I can solve this problem by adding sequence numbers to all sent packages. I can then process the received deltas with a higher sequence number once the complete state is read.

**Comment by aberres** [comment]
I think at least theoretically I might run into this issue as well when using wamp functionality:

Consider the case where you want to track registered clients.

When starting up you might have a function like this:
```
    async def query_already_registered_workers(self) -> None:
        registrations = await self.session.call('wamp.registration.list')

        for registration_id in registrations['exact']:
            details = await self.session.call('wamp.registration.get', registration_id)

            self.register_worker(registration_id, details)
```

and to track gone clients you do
```
    @wamp.subscribe('wamp.registration.on_delete')
    def unregister_worker(self, session_id, registration_id):
        # remove worker from internal datasctructure
        pass
```

What happens now if while `await self.session.call('wamp.registration.list')` is still pending while a worker is unregistered and the change is notified?

Then I have exactly the problem described above. First `unregister_worker` is called and then the complete list is handled. The worker is still considered to be alive. 

Am I misusing the API here?

**Comment by meejah** [comment]
If you just ran the example code as given, why do you have 2 things in the "all_changes" list?

Anyway, you could just always `publish` the latest state and use the "history" feature so that new clients will always get the last published state. If your state is really too big to do that, then yes you'll have to do "something" to deal with the possibility of a race between "ask for the current state" and "get some changes". That is, you can't know if another client has called "make_change" between when you asked for something and when you get the answer. In general you'll want to subscribe first, then ask for the current state but be prepared to throw away some changes (because they're on earlier versions of the state than you got in your answer).

You can do "acknowledged" publishes, but that just acks that the *router* received the publish. There is no way to get acks from each subscriber.

For your second comment, you're not mis-using the API per se, but you *can* control exactly when you subscribe to `on_delete` so you could choose to do that only after you've gotten your answer for the `list`. There's still a possible race there, though: while the router is processing `wamp.registration.list` a registration could be deleted for some reason after your answer is in-flight but before you subscribe to `on_delete`...Again, the right answer is to subscribe first but be prepared to get called before all your other async "setup" (`.list`, multiple `.get` calls) finishes.

**Comment by aberres** [comment]
> If you just ran the example code as given, why do you have 2 things in the "all_changes" list?

Sorry, had executed receiver.py two times.

> In general you'll want to subscribe first, then ask for the current state but be prepared to throw away some changes (because they're on earlier versions of the state than you got in your answer).

Yeap, this is how I would expect things to work. But now comes the tricky part this whole issue is about:  
One also needs to handle the case where a change is processed (not received) before the complete state is processed.  
The problem is that the processing order does not match the order of packages in the wire.

**Comment by aberres** [comment]
One more thing:  
As one cannot throw away all messages arrived before processing the current state I see problems with the `wamp.registration` API.

In my app, I added a "message sequence number" which is increased for every package sent. Clients can then drop all packages with a lower sequence number. This is not possible with the given API though.
